### ISSUE TITLE
Your wiki

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892017team1#1]
The wiki is ok.

Under Product Backlog we should have:

- Requirements discovery
- Product backlog
- Product backlog validation (missing)

Link to the code should be there as you will be using GitHub

Communications and tools can be updated. 

Please remove the descriptions once you begin to add your work.

**Comment by HanaStanojkovic** [comment]
Product Backlog validation is within the updated product backlog spreadsheet. All links have been added to wiki.
