### ISSUE TITLE
Feedback on the backlog

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892017team1#3]
I  posted comments in the Product Backlog.

https://docs.google.com/spreadsheets/d/1Saza3eNxHlmFdCP3jWy_LpQ8PvAbUBe_44Z4GgVm_18/edit#gid=1063441207

Are you focusing on Beijing only?

This is not consistent with the description on the wiki.

The 4 team members should read the Product Backlog.

There are repetitions of US.

The priorities should be checked. You will implement the high priority US first. Are all these US high priority?

The template for US was not always respected.

**Comment by HanaStanojkovic** [comment]
We are only focusing on Beijing. The wiki has since been updated. The backlog has been updated, repetitive US have been removed and priorities have been edited.
